version: "3.0"
services:
  redis:
    image: redis
    networks:
      - custom

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    networks:
      - custom

  sentry:
    image: sentry
    links:
      - redis
      - postgres
    ports:
      - "9000:9000"
    environment:
#      SENTRY_SECRET_KEY: '!!!SECRET!!!'
      SENTRY_SECRET_KEY: 'bqo+8t-02y!6xy4lre1+1-sj=e&ci1eoq_azmae2gdqwvg*=^('
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
    networks:
      - custom

  cron:
    image: sentry
    links:
      - redis
      - postgres
    command: "sentry run cron"
    environment:
#      SENTRY_SECRET_KEY: '!!!SECRET!!!'
      SENTRY_SECRET_KEY: 'bqo+8t-02y!6xy4lre1+1-sj=e&ci1eoq_azmae2gdqwvg*=^('
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
    networks:
      - custom

  worker:
    image: sentry
    links:
      - redis
      - postgres
    command: "sentry run worker"
    environment:
#      SENTRY_SECRET_KEY: '!!!SECRET!!!'
      SENTRY_SECRET_KEY: 'bqo+8t-02y!6xy4lre1+1-sj=e&ci1eoq_azmae2gdqwvg*=^('
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
    networks:
      - custom

networks:
  custom:
    driver: bridge
